services:
  - type: web
    name: waten
    env: node
    buildCommand: npm install && npm run postinstall
    startCommand: node server.js
    # Uncomment the following lines to persist data if using a PAID Render plan:
    # disk:
    #   name: data
    #   mountPath: /data
    #   sizeGB: 1
    # envVars:
    #   - key: DATA_DIR
    #     value: /data
